修复class列表窗口销毁时触发lambda报错
TypeError: <lambda>() missing 1 required positional argument: 'event'
应该是DnD 的<Destroy>lambda 绑定清理不干净导致的时不时报错 改成具体函数处理